name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-Linux-x86_64.sh
          sudo mkdir /opt/cmake
          sudo sh cmake-3.19.2-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
          echo "/opt/cmake/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: cmake -S . -B build
        
      - name: Build
        run: cmake --build build
        
      - name: Run tests
        run: ctest --test-dir build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpleFactoryExecutable
          path: build/SimpleFactoryExecutable
          
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: build/Testing/Temporary
